# src/agents/critic-agent/agent.py
# DEFINITIVE "ATTRIBUTE_ERROR" FIX
#
# This final version corrects the AttributeError by changing `model.model_name`
# to the correct internal property `model._model_name` in the logging statements.
# This allows the agent to run without crashing.

import os
from fastapi import FastAPI, Request, HTTPException
from dotenv import load_dotenv
import vertexai
from vertexai.generative_models import GenerativeModel, Part
import json

# --- Configuration for Vertex AI (ADC) Environment ---
load_dotenv()

try:
    GCP_PROJECT_ID = os.environ['GOOGLE_CLOUD_PROJECT']
    GCP_REGION = os.environ['GOOGLE_CLOUD_LOCATION']
    vertexai.init(project=GCP_PROJECT_ID, location=GCP_REGION)
    print(f"✅ Vertex AI Initialized. Project: {GCP_PROJECT_ID}, Region: {GCP_REGION}")
except KeyError as e:
    print(f"❌ CRITICAL ERROR: Environment variable {e} not found.")
    GCP_PROJECT_ID = None
    GCP_REGION = None

# Configure the Gemini model with a higher token limit
generation_config = {
    "temperature": 0.3,
    "top_p": 1.0,
    "top_k": 32,
    "max_output_tokens": 2048,
}

model = GenerativeModel(
    model_name="gemini-2.5-flash", # Using the allowed model
    generation_config=generation_config
)

app = FastAPI(title="Critic Agent (Functional - GCP Native)")


def get_critic_prompt(analysis_json: str) -> str:
    """Creates a detailed, self-explanatory prompt for Gemini to evaluate the analysis."""
    return f"""
    You are a principal Site Reliability Engineer (SRE) at a major bank, acting as a "Critic Agent".
    Your task is to evaluate an automated root cause analysis generated by another AI.
    Your evaluation must be concise, direct, and focus on three key areas:

    1.  **Clarity:** Is the summary clear and easy for a human engineer to understand?
    2.  **Actionability:** Are the recommended actions specific, practical, and likely to resolve the issue or improve the situation?
    3.  **Evidence-based:** Does the analysis logically follow from the provided evidence?

    Here is the analysis to evaluate:
    ```json
    {analysis_json}
    ```

    You MUST provide your evaluation ONLY in a structured JSON format with the following keys:
    - "overall_assessment": A single sentence summarizing your verdict.
    - "clarity_score": An integer from 1 (unclear) to 5 (very clear).
    - "actionability_score": An integer from 1 (not actionable) to 5 (very actionable).
    - "evidence_score": An integer from 1 (not evidence-based) to 5 (strongly evidence-based).
    - "critique_notes": A brief bullet point list of your reasoning.
    """


@app.post("/evaluate-analysis")
async def evaluate_analysis(request: Request):
    """Receives analysis, sends it to Gemini for critique, and returns the evaluation."""
    print("\n================================================================================")
    print("🕵️  CRITIC AGENT ACTIVATED: Evaluating AI-generated analysis for validity.")
    print("================================================================================")

    try:
        data = await request.json()
        print("\n[Step 1] Received the following analysis from the Orchestrator:")
        print("--------------------------------------------------------------------------------")
        print(json.dumps(data, indent=2))
        print("--------------------------------------------------------------------------------\n")
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON payload.")

    if not GCP_PROJECT_ID or not GCP_REGION:
        print("❌ Cannot proceed: GCP Project ID/Region not configured.")
        return {"status": "evaluation_failed", "reason": "Agent not configured."}

    prompt = get_critic_prompt(json.dumps(data, indent=2))
    
    # --- THIS IS THE FIX ---
    print(f"[Step 2] Constructing a prompt for '{model._model_name}' to act as a senior SRE...")
    print("   -> Prompt asks Gemini to rate Clarity, Actionability, and Evidence.\n")

    print(f"[Step 3] Calling the '{model._model_name}' model via Vertex AI...")
    # --- END OF FIX ---
    
    print("   -> Waiting for Gemini's expert evaluation...")

    try:
        response = model.generate_content([Part.from_text(prompt)])
        response_text = response.text
        
        print(f"   -> Raw response from Gemini received:\n---\n{response_text}\n---\n")

        json_start = response_text.find('{')
        json_end = response_text.rfind('}') + 1
        
        if json_start != -1 and json_end != 0:
            clean_json_str = response_text[json_start:json_end]
            evaluation_result = json.loads(clean_json_str)
            print("   ✅ Gemini response parsed successfully.\n")
        else:
            raise ValueError("No valid JSON object found in Gemini response.")

        print("[Step 4] Gemini's final evaluation:")
        print("--------------------------------------------------------------------------------")
        print(json.dumps(evaluation_result, indent=2))
        print("--------------------------------------------------------------------------------\n")
        
        print("✅ CRITIC AGENT TASK COMPLETE: Evaluation logged and returned to Orchestrator.")
        print("================================================================================\n")
        
        return {"status": "evaluation logged", "evaluation": evaluation_result}

    except Exception as e:
        print(f"❌ An error occurred while communicating with Vertex AI or parsing the response: {e}")
        return {"status": "evaluation_failed", "reason": str(e)}


@app.get("/health")
def health():
    """Health check endpoint."""
    return {"status": "healthy"}